name: ampoule-temp-control
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - scipy
  - pyserial
  - pip
  - pip:
    - dotenv
    - labjack-ljm
    - picosdk
    - pyserial
